name: teaching-talks

channels:
- conda
- conda-forge
- r

dependencies:
- numpy
- libgfortran
- pandas
- pandas-datareader
- flake8
- pytest
- scipy=1.2.1
- jupyterlab
- matplotlib
- seaborn
- jupyter
- pip
- numba
- mpi4py
- pygraphviz
- rise
- r-essentials
- rpy2
- simplegeneric
- pip:
        - linearmodels
        - jupyter
