name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: create conda env
      run: |
        sudo apt-get update
        sudo apt-get install texlive texlive-science texlive-latex-extra texlive-bibtex-extra texlive-fonts-extra
        sudo add-apt-repository ppa:malteworld/ppa
        sudo apt update
        sudo apt-get install pdftk
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a
        PATH="$HOME/miniconda/bin:$PATH"
        conda env create -f configurations/environment.yml
        source activate teaching-talks 
    - name: compile latex \#1
      run: |
        texhash
        source .envrc
        run-project
        shell: python
    - name: compile latex \#2
      run: |
        texhash
        source .envrc
        run-project
        shell: python
    - name: compile latex \#3
      run: |
        texhash
        source .envrc
        run-project
        shell: python
