name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install latex dependencies
      run: |
        sudo apt-get update
        sudo apt-get install texlive texlive-science texlive-latex-extra texlive-bibtex-extra texlive-fonts-extra
        sudo add-apt-repository ppa:malteworld/ppa
        sudo apt update
        sudo apt-get install pdftk 
    - name: create conda env
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
           activate-environment: teaching-talks
           environment-file: configurations/example-environment.yml
           python-version: 3.5
           auto-activate-base: false
    - name: compile latex \#1
      run: |
        texhash
        source .envrc
        run-project
        shell: python
    - name: compile latex \#2
      run: |
        texhash
        source .envrc
        run-project
        shell: python
    - name: compile latex \#3
      run: |
        texhash
        source .envrc
        run-project
        shell: python
