name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: create conda env
      run: |
        sudo apt-get update
        sudo apt-get install texlive texlive-science texlive-latex-extra texlive-bibtex-extra texlive-fonts-extra
        sudo add-apt-repository ppa:malteworld/ppa
        sudo apt update
        sudo apt-get install pdftk
        pip install matplotlib
        ./scripts/travis_miniconda.sh
        PATH="$HOME/miniconda/bin:$PATH"
        conda env create -f configurations/environment.yml
        source activate teaching-talks 
    - name: compile latex \#1
      run: |
        texhash
        source .envrc
        run-project
        shell: python
    - name: compile latex \#2
      run: |
        texhash
        source .envrc
        run-project
        shell: python
    - name: compile latex \#3
      run: |
        texhash
        source .envrc
        run-project
        shell: python
