name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
           activate-environment: test-teach
           environment-file: test.yml
           python-version: 3.7
           auto-activate-base: false

    - name: install latex dependencies
      run: |
        sudo add-apt-repository ppa:malteworld/ppa
        sudo apt-get update
        sudo apt-get install texlive texlive-science texlive-latex-extra texlive-bibtex-extra texlive-fonts-extra
        sudo texhash
    - name: pytest
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        git submodule update --init --recursive
        py.test
    - name: run project
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        run-project
